version: "3.5"

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile_server
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    volumes:
      - ./server/src:/app/src

  client:
    build:
      context: .
      dockerfile: docker/Dockerfile_vue
    command: npm run dev
    ports:
      - 8081:8080
    # network_mode: host
    depends_on:
      - server
    volumes:
      - ./vue/src:/app/src
      - ./vue/tests:/app/tests